enabled_models:
  - yolo11n
  - yolo11n_seg
  - yolo11n_pose
  - yolo11n_obb
  - yolo11n_track
  # - yolo11s
  # - qwen3vl_caption_transformers
  # - qwen3vl_grounding_transformers
  # - qwen3vl_caption_api
  # - segment_anything_2
  # - segment_anything_3
  - segment_anything_3_video
  # - glm_4_6v_grounding_api